### PR TITLE
feat - added sort/filter functionalities in products page

### PR DESCRIPTION
**Pull request by akash-1318**
# Functionalities added -
1. Added sort by price
2. Added filter by categories
3. Filter by star ratings
4. Filter by price range
5. Change in Product Database

# Files to Check -
1. src/components/product-card/ProductCard.js
2. src/components/sidebar/Sidebar.js
3. src/contexts/product-context.js
4. src/reducers/product-reducer.js
5. src/utils/sort-and-filter/sort.js
6. src/utils/sort-and-filter/filter.js

https://user-images.githubusercontent.com/64393554/159165639-bf69e6e3-c584-4dda-b1ac-6b272d721081.mov

### CODE REVIEW

**Review by shrushti2000 — APPROVED** [review]
The code is well structured and folder structure is also good. 
Good naming conventions.  
Created seperate files for functions as well. 
Overall looks good to be merged. Great work

**Review by arjunbharti — APPROVED** [review]
One general suggestion: add comments for different functions. It makes the code more readable
Things I liked in your code: 

- You followed same pattern of exporting i.e { namedExport } throughout your code.
- No unnecessary comments
- Proper file structure

**Comment by akash-1318** [comment]
> The code is well structured and folder structure is also good. Good naming conventions. Created seperate files for functions as well. Overall looks good to be merged. Great work

Thanks for the review

**Comment by akash-1318** [comment]
> One general suggestion: add comments for different functions. It makes the code more readable Things I liked in your code:
> 
> * You followed same pattern of exporting i.e { namedExport } throughout your code.
> * No unnecessary comments
> * Proper file structure

Thanks for the review Arjun will surely look into your suggestion .

**Pull request merged**
